export const LINKS_PAGE_CONFIG = {
  company: {
    name: 'IT Services & Security',
    logoPath: '/images/logos/itss-logo.png',
    tagline: 'Seguridad y tecnología para negocios en Puerto Rico',
    subtagline: 'Residencial y Comercial · Trabajamos toda la isla',
  },

  links: [
    {
      id: 'whatsapp',
      label: 'Cotiza por WhatsApp',
      sublabel: 'Respuesta en menos de 24h',
      url: 'https://wa.me/19392842551?text=Hola%2C%20me%20interesa%20una%20cotización%20para%20mis%20servicios%20de%20seguridad.',
      icon: 'whatsapp',
      primary: true,
      external: true,
      analyticsEvent: 'linkhub_whatsapp_click',
      screenshotUrl: 'https://api.microlink.io?url=https%3A%2F%2Fwa.me%2F19392842551&screenshot=true&meta=false&embed=screenshot.url',
    },
    {
      id: 'website',
      label: 'Visita nuestro website',
      sublabel: 'itservicespr.com',
      url: 'https://itservicespr.com',
      icon: 'globe',
      primary: false,
      external: false,
      analyticsEvent: 'linkhub_website_click',
      screenshotUrl: 'https://api.microlink.io?url=https%3A%2F%2Fwww.itservicespr.com%2Fportafolio&screenshot=true&meta=false&embed=screenshot.url',
    },
    {
      id: 'instagram',
      label: 'Síguenos en Instagram',
      sublabel: '@itservicespr',
      url: 'https://www.instagram.com/itservicespr',
      icon: 'instagram',
      primary: false,
      external: true,
      analyticsEvent: 'linkhub_instagram_click',
      screenshotUrl: 'https://api.microlink.io?url=https%3A%2F%2Fwww.instagram.com%2Fitservicespr%2F&screenshot=true&meta=false&embed=screenshot.url',
    },
    {
      id: 'facebook',
      label: 'Síguenos en Facebook',
      sublabel: 'IT Services & Security',
      url: 'https://www.facebook.com/share/18mve48BQE/',
      icon: 'facebook',
      primary: false,
      external: true,
      analyticsEvent: 'linkhub_facebook_click',
      screenshotUrl: 'https://api.microlink.io?url=https%3A%2F%2Fwww.facebook.com%2Fprofile.php%3Fid%3D61567086793252&screenshot=true&meta=false&embed=screenshot.url',
    },
    {
      id: 'projects',
      label: 'Ver nuestros proyectos',
      sublabel: '120+ proyectos completados en PR',
      url: 'https://itservicespr.com/portafolio',
      icon: 'briefcase',
      primary: false,
      external: false,
      analyticsEvent: 'linkhub_projects_click',
      screenshotUrl: 'https://api.microlink.io?url=https%3A%2F%2Fwww.itservicespr.com%2Fportafolio&screenshot=true&meta=false&embed=screenshot.url',
    },
    {
      id: 'review',
      label: 'Déjanos una reseña en Google',
      sublabel: 'Tu opinión nos ayuda mucho',
      url: 'https://g.page/r/CfNReRiQQTnEAI/review',
      icon: 'star',
      primary: false,
      external: true,
      analyticsEvent: 'linkhub_google_review_click',
      screenshotUrl: 'https://api.microlink.io?url=https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3DIT%2BServices%2BSecurity%2BPuerto%2BRico&screenshot=true&meta=false&embed=screenshot.url',
    },
  ],
} as const

export type LinkItem = (typeof LINKS_PAGE_CONFIG.links)[number]
