export const LINKS_PAGE_CONFIG = {
  company: {
    name: 'IT Services & Security',
    logoPath: '/images/logos/itss-logo.png',
    tagline: 'Seguridad y tecnología para negocios en Puerto Rico',
    subtagline: 'Residencial y Comercial · Trabajamos toda la isla',
  },

  links: [
    {
      id: 'whatsapp',
      label: 'Cotiza por WhatsApp',
      sublabel: 'Respuesta en menos de 24h',
      url: 'https://wa.me/19392842551?text=Hola%2C%20me%20interesa%20una%20cotización%20para%20mis%20servicios%20de%20seguridad.',
      icon: 'whatsapp',
      primary: true,
      external: true,
      analyticsEvent: 'linkhub_whatsapp_click',
      preview: {
        bg: 'from-[#075E54] to-[#128C7E]',
        title: 'WhatsApp Business',
        description: 'Escríbenos directamente. Te respondemos en menos de 24 horas con tu cotización personalizada.',
        badge: '💬 Chat directo',
        darkText: false,
      },
    },
    {
      id: 'website',
      label: 'Visita nuestro website',
      sublabel: 'itservicespr.com',
      url: 'https://itservicespr.com',
      icon: 'globe',
      primary: false,
      external: false,
      analyticsEvent: 'linkhub_website_click',
      preview: {
        bg: 'from-blue-900 to-black',
        title: 'itservicespr.com',
        description: 'Conoce todos nuestros servicios: cámaras, redes, control de acceso y soporte técnico para negocios en PR.',
        badge: '🌐 Website oficial',
        darkText: false,
      },
    },
    {
      id: 'instagram',
      label: 'Síguenos en Instagram',
      sublabel: '@itservicespr',
      url: 'https://www.instagram.com/itservicespr',
      icon: 'instagram',
      primary: false,
      external: true,
      analyticsEvent: 'linkhub_instagram_click',
      preview: {
        bg: 'from-purple-600 via-pink-500 to-orange-400',
        title: '@itservicespr',
        description: 'Proyectos reales, instalaciones profesionales y consejos de seguridad para tu negocio.',
        badge: '📸 Instagram',
        darkText: false,
      },
    },
    {
      id: 'facebook',
      label: 'Síguenos en Facebook',
      sublabel: 'IT Services & Security',
      url: 'https://www.facebook.com/share/1EThrPqd8w/',
      icon: 'facebook',
      primary: false,
      external: true,
      analyticsEvent: 'linkhub_facebook_click',
      preview: {
        bg: 'from-blue-700 to-blue-900',
        title: 'IT Services & Security',
        description: 'Actualizaciones, proyectos completados y noticias del sector en nuestra página de Facebook.',
        badge: '👍 Facebook',
        darkText: false,
      },
    },
    {
      id: 'projects',
      label: 'Ver nuestros proyectos',
      sublabel: '120+ proyectos completados en PR',
      url: 'https://itservicespr.com/portafolio',
      icon: 'briefcase',
      primary: false,
      external: false,
      analyticsEvent: 'linkhub_projects_click',
      preview: {
        bg: 'from-gray-800 to-gray-950',
        title: 'Portafolio de proyectos',
        description: 'Más de 120 proyectos completados: cuarteles de policía, supermercados, edificios residenciales e instituciones.',
        badge: '🏗️ 120+ proyectos',
        darkText: false,
      },
    },
    {
      id: 'review',
      label: 'Déjanos una reseña en Google',
      sublabel: 'Tu opinión nos ayuda mucho',
      url: 'https://g.page/r/CfNReRiQQQTnEAI/review',
      icon: 'star',
      primary: false,
      external: true,
      analyticsEvent: 'linkhub_google_review_click',
      preview: {
        bg: 'from-gray-100 to-white',
        title: 'Google Reviews',
        description: '¿Trabajamos juntos? Tu reseña en Google ayuda a otros negocios a encontrarnos y confiar en nosotros.',
        badge: '⭐ Dejar reseña',
        darkText: true,
      },
    },
  ],
}

export type LinkItem = (typeof LINKS_PAGE_CONFIG.links)[0]
export type PreviewData = (typeof LINKS_PAGE_CONFIG.links)[0]['preview']
